### ISSUE TITLE
Transaction "Customer Reference Number" should permit spaces

### ISSUE THREAD

**Issue by bayprogrammer** [stechstudio/bai2#6]
The BAI2 specification only indicates that a Transaction (record-type 16) field should be alphanumeric and can be any length. It does not define the paramenters of "alphanumeric". See page 19 of the [BAI Cash Management Balance Reporting Specifications Version 2](https://www.bai.org/docs/default-source/libraries/site-general-downloads/cash_management_2005.pdf) specification.

We have observed spaces in the Customer Reference Number field in the wild at least one time, and I believe I have seen test data from other projects which also included spaces in this field.

We should relax our interpretation of the Customer Reference Number's alphanumeric-ness to include spaces.

**Comment by bayprogrammer** [comment]
Exception & trace received when trying to parse a file which contains spaces embedded within the Customer Reference Number field of a Transaction record:

```
$ bai2json file-with-issue.bai2
PHP Fatal error:  Uncaught STS\Bai2\Exceptions\MalformedInputException: Encountered issue trying to parse Transaction Field. Invalid field type: "Customer Reference Number" must be alpha-numeric when provided. in /home/zebdeos/.config/composer/vendor/stechstudio/bai2/src/Records/TryableParserRecordTrait.php:24
Stack trace:
#0 /home/zebdeos/.config/composer/vendor/stechstudio/bai2/src/Records/TransactionRecord.php(80): STS\Bai2\Records\TransactionRecord->generalizedTryParser('parser', 'Transaction', Object(Closure))
#1 /home/zebdeos/.config/composer/vendor/stechstudio/bai2/src/Records/TransactionRecord.php(33): STS\Bai2\Records\TransactionRecord->tryParser(Object(Closure))
#2 /home/zebdeos/.config/composer/vendor/stechstudio/bai2/src/Records/AccountRecord.php(46): STS\Bai2\Records\TransactionRecord->toArray()
#3 [internal function]: STS\Bai2\Records\AccountRecord->STS\Bai2\Records\{closure}(Object(STS\Bai2\Records\TransactionRecord))
#4 /home/zebdeos/.config/composer/vendor/stechstudio/bai2/src/Records/AccountRecord.php(47): array_map(Object(Closure), Array)
#5 /home/zebdeos/.config/composer/vendor/stechstudio/bai2/src/Records/GroupRecord.php(46): STS\Bai2\Records\AccountRecord->toArray()
#6 [internal function]: STS\Bai2\Records\GroupRecord->STS\Bai2\Records\{closure}(Object(STS\Bai2\Records\AccountRecord))
#7 /home/zebdeos/.config/composer/vendor/stechstudio/bai2/src/Records/GroupRecord.php(47): array_map(Object(Closure), Array)
#8 /home/zebdeos/.config/composer/vendor/stechstudio/bai2/src/Records/FileRecord.php(42): STS\Bai2\Records\GroupRecord->toArray()
#9 [internal function]: STS\Bai2\Records\FileRecord->STS\Bai2\Records\{closure}(Object(STS\Bai2\Records\GroupRecord))
#10 /home/zebdeos/.config/composer/vendor/stechstudio/bai2/src/Records/FileRecord.php(43): array_map(Object(Closure), Array)
#11 /home/zebdeos/.config/composer/vendor/stechstudio/bai2/bin/bai2json(33): STS\Bai2\Records\FileRecord->toArray()
#12 /home/zebdeos/.config/composer/vendor/bin/bai2json(107): include('/home/zebdeos/....')
#13 {main}
  thrown in /home/zebdeos/.config/composer/vendor/stechstudio/bai2/src/Records/TryableParserRecordTrait.php on line 24

Fatal error: Uncaught STS\Bai2\Exceptions\MalformedInputException: Encountered issue trying to parse Transaction Field. Invalid field type: "Customer Reference Number" must be alpha-numeric when provided. in /home/zebdeos/.config/composer/vendor/stechstudio/bai2/src/Records/TryableParserRecordTrait.php on line 24

STS\Bai2\Exceptions\MalformedInputException: Encountered issue trying to parse Transaction Field. Invalid field type: "Customer Reference Number" must be alpha-numeric when provided. in /home/zebdeos/.config/composer/vendor/stechstudio/bai2/src/Records/TryableParserRecordTrait.php on line 24

Call Stack:
    0.0001     414536   1. {main}() /home/zebdeos/.config/composer/vendor/bin/bai2json:0
    0.0002     418504   2. include('/home/zebdeos/.config/composer/vendor/stechstudio/bai2/bin/bai2json') /home/zebdeos/.config/composer/vendor/bin/bai2json:107
    0.0936    5974888   3. STS\Bai2\Records\FileRecord->toArray() /home/zebdeos/.config/composer/vendor/stechstudio/bai2/bin/bai2json:33
...
```
